/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Query = IDL.Record({
  'question' : IDL.Text,
  'userId' : IDL.Principal,
  'collegeId' : IDL.Nat,
});
export const Response = IDL.Record({
  'userQuery' : Query,
  'answer' : IDL.Text,
  'collegeId' : IDL.Nat,
});
export const College = IDL.Record({
  'id' : IDL.Nat,
  'faq' : IDL.Vec(IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })),
  'campusLife' : IDL.Text,
  'contactInfo' : IDL.Text,
  'courses' : IDL.Vec(IDL.Text),
  'applicationDeadlines' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'campusFacilities' : IDL.Text,
  'programs' : IDL.Vec(IDL.Text),
  'tuitionFees' : IDL.Text,
  'admissionsRequirements' : IDL.Text,
  'scholarships' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCollege' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })),
      ],
      [IDL.Nat],
      [],
    ),
  'askQuestion' : IDL.Func([IDL.Text, IDL.Nat], [Response], []),
  'deleteUserHistory' : IDL.Func([], [], []),
  'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'getCollege' : IDL.Func([IDL.Nat], [College], ['query']),
  'getUserHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Query)], ['query']),
  'searchCollegesByName' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
  'searchCollegesByProgram' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(College)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Query = IDL.Record({
    'question' : IDL.Text,
    'userId' : IDL.Principal,
    'collegeId' : IDL.Nat,
  });
  const Response = IDL.Record({
    'userQuery' : Query,
    'answer' : IDL.Text,
    'collegeId' : IDL.Nat,
  });
  const College = IDL.Record({
    'id' : IDL.Nat,
    'faq' : IDL.Vec(IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })),
    'campusLife' : IDL.Text,
    'contactInfo' : IDL.Text,
    'courses' : IDL.Vec(IDL.Text),
    'applicationDeadlines' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'campusFacilities' : IDL.Text,
    'programs' : IDL.Vec(IDL.Text),
    'tuitionFees' : IDL.Text,
    'admissionsRequirements' : IDL.Text,
    'scholarships' : IDL.Text,
  });
  
  return IDL.Service({
    'addCollege' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })),
        ],
        [IDL.Nat],
        [],
      ),
    'askQuestion' : IDL.Func([IDL.Text, IDL.Nat], [Response], []),
    'deleteUserHistory' : IDL.Func([], [], []),
    'getAllColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'getCollege' : IDL.Func([IDL.Nat], [College], ['query']),
    'getUserHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Query)], ['query']),
    'searchCollegesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(College)],
        ['query'],
      ),
    'searchCollegesByProgram' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(College)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };