/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface College {
  'id' : bigint,
  'faq' : Array<{ 'question' : string, 'answer' : string }>,
  'campusLife' : string,
  'contactInfo' : string,
  'courses' : Array<string>,
  'applicationDeadlines' : string,
  'name' : string,
  'description' : string,
  'campusFacilities' : string,
  'programs' : Array<string>,
  'tuitionFees' : string,
  'admissionsRequirements' : string,
  'scholarships' : string,
}
export interface Query {
  'question' : string,
  'userId' : Principal,
  'collegeId' : bigint,
}
export interface Response {
  'userQuery' : Query,
  'answer' : string,
  'collegeId' : bigint,
}
export interface _SERVICE {
  'addCollege' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<{ 'question' : string, 'answer' : string }>,
    ],
    bigint
  >,
  'askQuestion' : ActorMethod<[string, bigint], Response>,
  'deleteUserHistory' : ActorMethod<[], undefined>,
  'getAllColleges' : ActorMethod<[], Array<College>>,
  'getCollege' : ActorMethod<[bigint], College>,
  'getUserHistory' : ActorMethod<[Principal], Array<Query>>,
  'searchCollegesByName' : ActorMethod<[string], Array<College>>,
  'searchCollegesByProgram' : ActorMethod<[string], Array<College>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];