/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Query {
    question: string;
    userId: Principal;
    collegeId: bigint;
}
export interface Response {
    userQuery: Query;
    answer: string;
    collegeId: bigint;
}
export interface College {
    id: bigint;
    faq: Array<{
        question: string;
        answer: string;
    }>;
    campusLife: string;
    contactInfo: string;
    courses: Array<string>;
    applicationDeadlines: string;
    name: string;
    description: string;
    campusFacilities: string;
    programs: Array<string>;
    tuitionFees: string;
    admissionsRequirements: string;
    scholarships: string;
}
export interface backendInterface {
    addCollege(name: string, description: string, admissionsRequirements: string, courses: Array<string>, programs: Array<string>, campusFacilities: string, campusLife: string, applicationDeadlines: string, tuitionFees: string, scholarships: string, contactInfo: string, faq: Array<{
        question: string;
        answer: string;
    }>): Promise<bigint>;
    askQuestion(question: string, collegeId: bigint): Promise<Response>;
    deleteUserHistory(): Promise<void>;
    getAllColleges(): Promise<Array<College>>;
    getCollege(id: bigint): Promise<College>;
    getUserHistory(userId: Principal): Promise<Array<Query>>;
    searchCollegesByName(searchText: string): Promise<Array<College>>;
    searchCollegesByProgram(searchText: string): Promise<Array<College>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCollege(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: Array<string>, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: Array<{
        question: string;
        answer: string;
    }>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollege(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollege(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async askQuestion(arg0: string, arg1: bigint): Promise<Response> {
        if (this.processError) {
            try {
                const result = await this.actor.askQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askQuestion(arg0, arg1);
            return result;
        }
    }
    async deleteUserHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserHistory();
            return result;
        }
    }
    async getAllColleges(): Promise<Array<College>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllColleges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllColleges();
            return result;
        }
    }
    async getCollege(arg0: bigint): Promise<College> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollege(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollege(arg0);
            return result;
        }
    }
    async getUserHistory(arg0: Principal): Promise<Array<Query>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserHistory(arg0);
            return result;
        }
    }
    async searchCollegesByName(arg0: string): Promise<Array<College>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCollegesByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCollegesByName(arg0);
            return result;
        }
    }
    async searchCollegesByProgram(arg0: string): Promise<Array<College>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCollegesByProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCollegesByProgram(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
